spring:
  kafka:
#    bootstrap-servers: 192.168.1.100:9092,192.168.1.100:9093,192.168.1.100:9094
    bootstrap-servers: 192.168.201.37:9092

    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1

    consumer:
      enable-auto-commit: false
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 15000

#kafka:
#  topic:
#    group-id: topicGroupId
#    topic-name:
#      - topic1
#      - topic2
#      - topic3
kafka:
  topic:
    group-id: topicGroupId
    topic-name:
      - baidu-fusion-algorithm-events
